id: I077BBB5B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T01:28:28+00:00'
last_modified: '2022-06-09T08:02:15.348357+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181210
  title: རཏྣ་གླིང་པའི་གཏེར་ཆོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B631:
      image_group_id: I1KG16284
      title: Volume 1 of rat+na gling pa'i gter chos/
      total_pages: 1470
      order: 1
      base_file: B631.txt
    E08C:
      image_group_id: I1KG16285
      title: Volume 2 of rat+na gling pa'i gter chos/
      total_pages: 702
      order: 2
      base_file: E08C.txt
    29F9:
      image_group_id: I1KG16286
      title: Volume 3 of rat+na gling pa'i gter chos/
      total_pages: 206
      order: 3
      base_file: 29F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
