id: I077BBB5B
legacy_id: P007961
ocr_import_info:
  bdrc_scan_id: W1PD181210
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T01:26:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:19:44.844022+00:00'
last_modified: 2022-09-01 12:20:41.672235
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD181210
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1PD181210
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རཏྣ་གླིང་པའི་གཏེར་ཆོས།
  author: རཏྣ་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5235513722573146
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I1KG16284:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16284
      total_pages: 1470
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16284.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5432146965495926
    legacy_id: v001
  I1KG16285:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16285
      total_pages: 702
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG16285.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.47735222497768326
    legacy_id: v002
  I1KG16286:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16286
      total_pages: 206
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG16286.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5826060093039584
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
