id: P007961
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181210
  title: རཏྣ་གླིང་པའི་གཏེར་ཆོས།
  author: ''
  volumes:
    cc764da0612d476c896ca282d19f7719:
      image_group_id: I1KG16284
      title: ''
      volume_number: 1
      total_pages: 1470
    525896332e32408f8598d809583d7e56:
      image_group_id: I1KG16285
      title: ''
      volume_number: 2
      total_pages: 702
    e1b923b5ea2545c2a8783675f30d63ed:
      image_group_id: I1KG16286
      title: ''
      volume_number: 3
      total_pages: 206
ebook_metadata:
  title: རཏྣ་གླིང་པའི་གཏེར་ཆོས།
  author: ''
  sku: P007961
  cover: cover.jpg
  layers:
  - pagination
